env:
  browser: true
  es6: true
  node: true
extends: [
  'plugin:react/recommended',
  'prettier/@typescript-eslint',
  'plugin:@typescript-eslint/recommended'
]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  '@typescript-eslint/indent': [2, 2]
  '@typescript-eslint/explicit-function-return-type': 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
